version: "3.4"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - shared:/app/dist/1851/browser

  web:
    image: nginx:1.19.1-alpine
    volumes:
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
      - shared:/app/dist/1851/browser
    ports:
      - 80:80


volumes:
  shared: