version: "3.4"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile

  web:
    image: nginx:1.19.1-alpine
    volumes:
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80